apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-app
  namespace: default
  labels:
    app: rollouts-app
spec:
  selector:
    matchLabels:
      app: rollouts-app
  replicas: 5 # 定义5个副本
  strategy: # 定义升级策略
    canary: # 金丝雀发布
      steps: # 发布的节奏
        - setWeight: 20
        - pause: {} # 会一直暂停
        - setWeight: 40
        - pause: { duration: 10 } # 暂停10s
        - setWeight: 60
        - pause: { duration: 10 }
        - setWeight: 80
        - pause: { duration: 10 }
  template:
    metadata:
      labels:
        app: rollouts-app
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: rollouts-app
        image: container-registry.tencentcloudcr.com/tools/argoproj-rollouts-demo:blue
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: rollouts-app
  namespace: default
spec:
  selector:
    app: rollouts-app
  type: ClusterIP
  ports:
  - name: rollouts-app
    protocol: TCP
    port: 8080
    targetPort: 8080
---
# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollouts-app
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: rollouts-app.orvibo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rollouts-app
            port:
              number: 8080
---